// src/components/ProjectList/ProjectList.js
import React from 'react';
import { useProject } from '../../context/ProjectContext';
import { FiFolder, FiClock, FiDownload, FiTrash2, FiEye, FiCode } from 'react-icons/fi';
import { saveAs } from 'file-saver';
import JSZip from 'jszip';
import './ProjectList.css';

const ProjectList = ({ onProjectSelect }) => {
  const { projects, deleteProject } = useProject();

  const handleDownload = async (project) => {
    const zip = new JSZip();
    
    // Add files to zip
    zip.file("index.html", project.html);
    zip.file("styles.css", project.css);
    zip.file("script.js", project.js);
    zip.file("README.md", `# ${project.name}\n\nGenerated by AI Website Builder\n\n${project.description}`);
    
    // Generate and download zip
    const content = await zip.generateAsync({ type: "blob" });
    saveAs(content, `${project.name.toLowerCase().replace(/\s+/g, '-')}.zip`);
  };

  const handlePreview = (project) => {
    onProjectSelect(project);
  };

  const formatDate = (dateString) => {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric'
    });
  };

  const getStatusColor = (status) => {
    switch (status) {
      case 'completed': return '#10B981';
      case 'generating': return '#F59E0B';
      case 'failed': return '#EF4444';
      default: return '#6B7280';
    }
  };

  return (
    <div className="project-list">
      <div className="list-header">
        <h1>Recent Projects</h1>
        <p className="subtitle">All your generated websites in one place</p>
      </div>

      {projects.length === 0 ? (
        <div className="empty-state">
          <FiFolder className="empty-icon" />
          <h3>No projects yet</h3>
          <p>Create your first website using the New Project tab</p>
        </div>
      ) : (
        <div className="projects-grid">
          {projects.map((project) => (
            <div key={project.id} className="project-card">
              <div className="project-card-header">
                <div className="project-info">
                  <h3 className="project-name">{project.name}</h3>
                  <div className="project-meta">
                    <span className="project-date">
                      <FiClock /> {formatDate(project.createdAt)}
                    </span>
                    <span 
                      className="project-status" 
                      style={{ color: getStatusColor(project.status) }}
                    >
                      ● {project.status}
                    </span>
                  </div>
                </div>
                
                <div className="project-actions">
                  <button 
                    className="action-btn preview-btn"
                    onClick={() => handlePreview(project)}
                    title="Preview"
                  >
                    <FiEye />
                  </button>
                  
                  <button 
                    className="action-btn code-btn"
                    onClick={() => handlePreview(project)}
                    title="View Code"
                  >
                    <FiCode />
                  </button>
                  
                  <button 
                    className="action-btn download-btn"
                    onClick={() => handleDownload(project)}
                    title="Download"
                    disabled={project.status !== 'completed'}
                  >
                    <FiDownload />
                  </button>
                  
                  <button 
                    className="action-btn delete-btn"
                    onClick={() => deleteProject(project.id)}
                    title="Delete"
                  >
                    <FiTrash2 />
                  </button>
                </div>
              </div>
              
              <div className="project-description">
                <p>{project.description}</p>
              </div>
              
              <div className="project-tags">
                {Object.entries(project.features || {})
                  .filter(([_, value]) => value)
                  .map(([key]) => (
                    <span key={key} className="tag">
                      {key.replace(/([A-Z])/g, ' $1')}
                    </span>
                  ))}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default ProjectList;